---
title: "MDPW"
author: "indryanisutisna"
date: "2024-08-26"
output:
  html_document: default
  word_document: default
---
TUGAS MPDW Kelompok 1

```{r}
library(readxl)
data <- read_excel("C:/Users/Irsyad Parama/Downloads/data 5 section.xlsx", sheet = "2")
head(data)
```

```{r}
library(forecast)
library(TTR)
library(graphics)
library(TSA)
```

```{r}
str(data)
dim(data)
head(data)
```

```{r}
data.ts <- ts(data$'Close')

summary(data.ts)
```

```{r}
ts.plot(data.ts, xlab="Date", ylab="Close", main="Time Series Plot")
points(data.ts)
```

```{r}
training_ma <- data[2:170,]
testing_ma <- data[171:211,]
View(testing_ma)
train_ma.ts <- ts(training_ma$'Close')
test_ma.ts <- ts(testing_ma$'Close')
```

```{r}
plot(data.ts, col="red",main="Plot semua data")
points(data.ts)
```

```{r}
plot(train_ma.ts, col="blue",main="Plot data latih")
points(train_ma.ts)
```

```{r}
plot(test_ma.ts, col="yellow",main="Plot data uji")
points(test_ma.ts)
```

```{r}
library(ggplot2)
# Ensure the data is sorted by the 'Waktu' column
training_ma$Date <- as.Date(training_ma$Date, format = "%d-%m-%Y")
testing_ma$Date <- as.Date(testing_ma$Date, format = "%d-%m-%Y")
training_ma <- training_ma[order(training_ma$Date), ]
testing_ma <- testing_ma[order(testing_ma$Date), ]

# Plot data with ggplot2
ggplot() + 
  geom_line(data = training_ma, aes(x = Date, y = `Close`, col = "Data Latih", group = 1)) +
  geom_line(data = testing_ma, aes(x = Date, y = `Close`, col = "Data Uji", group = 1)) +
  labs(x = "Periode Waktu", y = "Close", color = "Legend") +
  scale_colour_manual(name = "Legend", breaks = c("Data Latih", "Data Uji"),
                      values = c("blue", "red")) + 
  theme_bw() + 
  theme(legend.position = "bottom",
        plot.caption = element_text(hjust = 0.5, size = 12))

```

```{r}
data.sma<-SMA(train_ma.ts, n=3)
data.sma
```

```{r}
data.ramal<-c(NA,data.sma)
```

```{r}
data.gab<-cbind(aktual=c(data.ts,rep(NA,42)),pemulusan=c(data.sma,rep(NA,42)),ramalan=c(data.ramal,rep(data.ramal[length(data.ramal)],20)))
```

```{r}
ts.plot (data.ts,xlab="periode  waktu",ylab="Bagi hasil",  col="blue",lty=3)
points(data.ts)
lines (data.gab[,2],col="red",lwd=2)
lines (data.gab[,3],col="yellow",lwd= 2)
title("Rataan bergerak Sederhana n=3",cex.main=1,font.main=4 ,col.main="black")
```

```{r}
error_train.sma = train_ma.ts - data.ramal[1:length(train_ma.ts)]
SSE_train.sma = sum(error_train.sma[4:length(train_ma.ts)]^2)
MSE_train.sma = mean(error_train.sma[4:length(train_ma.ts)]^2)
MAPE_train.sma = mean(abs((error_train.sma[4:length(train_ma.ts)] / train_ma.ts[4:length(train_ma.ts)]) * 100))

akurasi_train.sma <- matrix(c(SSE_train.sma, MSE_train.sma, MAPE_train.sma))
row.names(akurasi_train.sma) <- c("SSE", "MSE", "MAPE")
colnames(akurasi_train.sma) <- c("Akurasi m = 3")
akurasi_train.sma
```

```{r}
# Calculate the error
error_test.sma <- test_ma.ts - data.gab[81:99, 3]

# Check for missing values and handle them
error_test.sma <- na.omit(error_test.sma)

# Calculate SSE and MSE
SSE_test.sma <- sum(error_test.sma^2)
MSE_test.sma <- mean(error_test.sma^2)

# Calculate MAPE, with a small constant added to avoid division by zero
MAPE_test.sma <- mean(abs((error_test.sma / (test_ma.ts + 1e-8)) * 100))

# Create the accuracy matrix
akurasi_test.sma <- matrix(c(SSE_test.sma, MSE_test.sma, MAPE_test.sma), nrow = 3)
row.names(akurasi_test.sma) <- c("SSE", "MSE", "MAPE")
colnames(akurasi_test.sma) <- c("Akurasi m = 3")

# Print the accuracy matrix
akurasi_test.sma

```

```{r}
dma <- SMA(data.sma, n = 3)
At <- 2*data.sma - dma
Bt <- 2/(4-1)*(data.sma - dma)
data.dma<- At+Bt
data.ramal2<- c(NA, data.dma)

t = 1:42
f = c()

for (i in t) {
  f[i] = At[length(At)] + Bt[length(Bt)]*(i)
}

data.gab2 <- cbind(aktual = c(train_ma.ts,rep(NA,42)), pemulusan1 = c(data.sma,rep(NA,42)),pemulusan2 = c(data.dma, rep(NA,42)),At = c(At, rep(NA,42)), Bt = c(Bt,rep(NA,42)),ramalan = c(data.ramal2, f[-1]))
data.gab2
```

```{r}
ts.plot(data.ts, xlab="Time Period ", ylab="Sales", main= "DMA N=3 Data Average Temperature")
points(data.ts)
lines(data.gab2[,3],col="green",lwd=2)
lines(data.gab2[,6],col="red",lwd=2)
legend("topleft",c("data aktual","data pemulusan","data peramalan"), lty=8, col=c("black","green","red"), cex=0.5)
```

```{r}
error_train.dma = train_ma.ts-data.ramal2[1:length(train_ma.ts)]
SSE_train.dma = sum(error_train.dma[6:length(train_ma.ts)]^2)
MSE_train.dma = mean(error_train.dma[6:length(train_ma.ts)]^2)
MAPE_train.dma = mean(abs((error_train.dma[6:length(train_ma.ts)]/train_ma.ts[6:length(train_ma.ts)])*100))

akurasi_train.dma <- matrix(c(SSE_train.dma, MSE_train.dma, MAPE_train.dma))
row.names(akurasi_train.dma)<- c("SSE", "MSE", "MAPE")
colnames(akurasi_train.dma) <- c("Akurasi m = 3")
akurasi_train.dma
```

```{r}
# Calculate the error
error_test.dma <- test_ma.ts - data.gab2[81:99, 6]

# Check for missing values and handle them by removing NA
error_test.dma <- na.omit(error_test.dma)

# Calculate SSE and MSE
SSE_test.dma <- sum(error_test.dma^2)
MSE_test.dma <- mean(error_test.dma^2)

# Calculate MAPE, with a small constant added to avoid division by zero
MAPE_test.dma <- mean(abs((error_test.dma / (test_ma.ts + 1e-8)) * 100))

# Create the accuracy matrix
akurasi_test.dma <- matrix(c(SSE_test.dma, MSE_test.dma, MAPE_test.dma), nrow = 3)
row.names(akurasi_test.dma) <- c("SSE", "MSE", "MAPE")
colnames(akurasi_test.dma) <- c("Akurasi m = 4")

# Print the accuracy matrix
akurasi_test.dma

```

```{r}
training_exp <- data[1:168,]
testing_exp <- data[168:210,]

train_ma.exp <- ts(training_exp$'Close')
test_ma.exp <- ts(testing_exp$'Close')
```

```{r}
plot(data.ts, col="black",main="Plot semua data")
points(data.ts)
```

```{r}
plot(train_ma.exp, col="red",main="Plot data latih")
points(train_ma.exp)
```

```{r}
plot(test_ma.exp, col="blue",main="Plot data uji")
points(test_ma.exp)
```

```{r}
ggplot() + 
  geom_line(data = training_exp, aes(x = Date, y = `Close`, col = "Data Latih", group = 1)) +
  geom_line(data = testing_exp, aes(x = Date, y = `Close`, col = "Data Uji", group = 1)) +
  labs(x = "Periode Waktu", y = "Close", color = "Legend") +
  scale_colour_manual(name = "Legend", breaks = c("Data Latih", "Data Uji"),
                      values = c("blue", "red")) + 
  theme_bw() + 
  theme(legend.position = "bottom",
        plot.caption = element_text(hjust = 0.5, size = 12))
```

```{r}
ses1 <- ses(train_ma.exp, h = 20, alpha = 0.2)
plot(ses1)
```

```{r}
ses1
```

```{r}
ses2<- ses(train_ma.exp, h = 20, alpha = 0.7)
plot(ses2)
```

```{r}
ses2
```

```{r}
time_series_data <- ts(training_exp$'Close', start = c(2012, 27), frequency = 52) 

model1 <- HoltWinters(time_series_data, alpha = 0.4, beta = FALSE, gamma = FALSE)
plot(model1) 
```

```{r}
#Alpha 0,2
ramalan1<- forecast(ses1, h=20)
ramalan1
```

```{r}
#Cara Manual
sisaan1 <- residuals(ramalan1)
SSE.1=sum(sisaan1[2:length(train_ma.exp)]^2)
SSE.1
```

```{r}
MSE.1 = SSE.1/length(train_ma.exp)
MSE.1
```

```{r}
MAPE.1 = sum(abs(sisaan1[2:length(train_ma.exp)]/train_ma.exp[2:length(train_ma.exp)])* 100)/length(train_ma.exp)
MAPE.1
```

```{r}
akurasi.1 <- matrix(c(SSE.1,MSE.1,MAPE.1))
row.names(akurasi.1)<- c("SSE", "MSE", "MAPE")
colnames(akurasi.1) <- c("Akurasi lamda=0.2")
akurasi.1
```

```{r}
#alpha 0,7

ramalan2 <- forecast(ses2, h=20)
ramalan2
```

```{r}
fitted2<-ramalan2$fitted
sisaan2<-ramalan2$residuals
head(sisaan2)
```

```{r}
resid2<-training_exp$"Close"-ramalan2$fitted
head(resid2)
```

```{r}
SSE.2=sum(sisaan2[2:length(train_ma.exp)]^2)
SSE.2
```

```{r}
MSE.2 = SSE.2/length(train_ma.exp)
MSE.2
```

```{r}
MAPE.2 = sum(abs(sisaan2[2:length(train_ma.exp)]/train_ma.exp[2:length(train_ma.exp)])*100)/length(train_ma.exp)
MAPE.2
```

```{r}
akurasi.2 <- matrix(c(SSE.2,MSE.2,MAPE.2))
row.names(akurasi.2)<- c("SSE", "MSE", "MAPE")
colnames(akurasi.2) <- c("Akurasi lamda=0.7")
akurasi.2
```

```{r}
ses.opt <- ses(train_ma.exp, h = 20, alpha = NULL)
plot(ses.opt)
```

```{r}
ses.opt
```       

```{r}
sesopt<- HoltWinters(train_ma.exp, gamma = FALSE, beta = FALSE,alpha = NULL)
sesopt
```

```{r}
plot(sesopt)
```

```{r}
ramalanopt<- forecast(sesopt, h=43)
ramalanopt
```

```{r}
fittedopt<-ramalanopt$fitted
sisaanopt<-ramalanopt$residuals
head(sisaanopt)
```

```{r}
residopt<-training_exp$"Close"-ramalanopt$fitted
head(residopt)
```

```{r}
SSEopt=sum(sisaanopt[2:length(train_ma.exp)]^2)
SSEopt
```

```{r}
MSEopt = SSEopt/length(train_ma.exp)
MSEopt
```

```{r}
MAPEopt= sum(abs(sisaanopt[2:length(train_ma.exp)]/train_ma.exp[2:length(train_ma.exp)])*100)/length(train_ma.exp)
MAPEopt
```

```{r}
akurasiopt<- matrix(c(SSEopt,MSEopt,MAPEopt))
row.names(akurasiopt)<- c("SSE", "MSE", "MAPE")
colnames(akurasiopt) <- c("Akurasi lamda=optimal")
akurasiopt
```

```{r}
accuracy(ramalanopt,testing_exp$'Close')
```

```{r}
#Lamda=0.2 dan gamma=0.2
des.1<- HoltWinters(train_ma.exp, gamma = FALSE, beta = 0.2, alpha = 0.2)
plot(des.1)
```

```{r}
ramalandes1<- forecast(des.1, h=43)
ramalandes1
```
```{r}
#Lamda=0.6 dan gamma=0.3
des.2<- HoltWinters(train_ma.exp, gamma = FALSE, beta = 0.5, alpha = 0.6)
plot(des.2)
```

```{r}
ramalandes2<- forecast(des.2, h=43)
ramalandes2
```
```{r}
plot(data.ts)
lines(des.1$fitted[,1], lty=2, col="blue")
lines(ramalandes1$mean, col="red")
```

```{r}
des.opt<- HoltWinters(train_ma.exp, gamma = FALSE)
des.opt
```
```{r}
plot(des.opt)
```
```{r}
ramalandesopt<- forecast(des.opt, h=43)
ramalandesopt
```
Cek Akurasi

```{r}
ssedes.train1 <- des.1$SSE
msedes.train1 <- ssedes.train1 / length(train_ma.exp)
sisaandes1 <- ramalandes1$residuals
head(sisaandes1)
```
```{r}
mapedes.train1 <- sum(abs(sisaandes1[3:length(train_ma.exp)] / train_ma.exp[3:length(train_ma.exp)])
                      *100) / length(train_ma.exp)

akurasides.1 <- matrix(c(ssedes.train1, msedes.train1, mapedes.train1))
row.names(akurasides.1) <- c("SSE", "MSE", "MAPE")
colnames(akurasides.1) <- c("Akurasi lamda=0.2 dan gamma=0.2")
akurasides.1
```

```{r}
ssedes.train2 <- des.2$SSE
msedes.train2 <- ssedes.train2 / length(train_ma.exp)
sisaandes2 <- ramalandes2$residuals
head(sisaandes2)
```

```{r}
mapedes.train2 <- sum(abs(sisaandes2[3:length(train_ma.exp)] / train_ma.exp[3:length(train_ma.exp)])
                      *100) / length(train_ma.exp)

akurasides.2 <- matrix(c(ssedes.train2, msedes.train2, mapedes.train2))
row.names(akurasides.2) <- c("SSE", "MSE", "MAPE")
colnames(akurasides.2) <- c("Akurasi lamda=0.6 dan gamma=0.5")
akurasides.2
```

```{r}
selisihdes1 <- ramalandes1$mean - testing_exp$`Close`
selisihdes1
```

```{r}
SSEtestingdes1 <- sum(selisihdes1^2)
SSEtestingdes1
MSEtestingdes1 <- SSEtestingdes1 / length(testing_exp$`Close`)
MAPEtestingdes1 <- sum(abs(selisihdes1 / testing_exp$`Close`) * 100) / length(testing_exp$`Close`)

selisihdes2 <- ramalandes2$mean - testing_exp$`Close`
selisihdes2
```

```{r}
SSEtestingdes2 <- sum(selisihdes2^2)
MSEtestingdes2 <- SSEtestingdes2 / length(testing_exp$`Close`)
MAPEtestingdes2 <- sum(abs(selisihdes2 / testing_exp$`Close`) * 100) / length(testing_exp$`Close`)

selisihdesopt <- ramalandesopt$mean - testing_exp$`Close`
selisihdesopt
```

```{r}
SSEtestingdesopt <- sum(selisihdesopt^2)
MSEtestingdesopt <- SSEtestingdesopt / length(testing_exp$`Close`)
MAPEtestingdesopt <- sum(abs(selisihdesopt / testing_exp$`Close`) * 100) / length(testing_exp$`Close`)

akurasitestingdes <-
  matrix(c(SSEtestingdes1, MSEtestingdes1, MAPEtestingdes1, SSEtestingdes2, MSEtestingdes2,
           MAPEtestingdes2, SSEtestingdesopt, MSEtestingdesopt, MAPEtestingdesopt),
         nrow = 3, ncol = 3)
row.names(akurasitestingdes) <- c("SSE", "MSE", "MAPE")
colnames(akurasitestingdes) <- c("des ske1", "des ske2", "des opt")
akurasitestingdes
```
```{r}
MSEfull <-
  matrix(c(MSE.1,MSE.2,MSEopt,MSEtestingdes1,MSEtestingdes2,
           MSEtestingdesopt),nrow=3,ncol=2)
row.names(MSEfull)<- c("ske 1", "ske 2", "ske opt")
colnames(MSEfull) <- c("ses","des")
MSEfull
```
```{r}
library("rio")
```

```{r}
trainwin <- data[1:80,]
testwin <- data[81:99,]



trainter <- ts(trainwin$'Close', frequency = 10) #start = c(tahun mulai, minggu ke-berapa), frequency = 52 karena per minggufrequency=52)
testter <- ts(testwin$'Close', frequency = 10) #start = c(tahun mulai, minggu ke-berapa), frequency = 52 karena per minggu52)
```

```{r}
winter1 <- HoltWinters(trainter, alpha = 0.2, beta = 0.1, gamma = 0.1, seasonal = "additive")
winter1$fitted
```
```{r}
xhat1 <- winter1$fitted[,2]

# Apply Holt-Winters method with optimized parameters
winter1.opt <- HoltWinters(trainter, alpha = NULL, beta = NULL, gamma = NULL, seasonal = "additive")
winter1.opt
```
```{r}
winter1.opt$fitted
```
```{r}
xhat1.opt <- winter1.opt$fitted[,2]  # Corrected line with the closing bracket
```

```{r}
forecast1 <- predict(winter1, n.ahead = 19)
forecast1.opt <- predict(winter1.opt, n.ahead = 19)
```

```{r}
#Plot time series
plot(trainter,main="Winter 0.2;0.1;0.1",type="l",col="black",
     xlim=c(1,25),pch=12)
lines(xhat1,type="l",col="red")
lines(xhat1.opt,type="l",col="blue")
lines(forecast1,type="l",col="red")
lines(forecast1.opt,type="l",col="blue")
legend("topleft",c("Actual Data",expression(paste(winter1)),
                   expression(paste(winter1.opt))),cex=0.5,
       col=c("black","red","blue"),lty=1)
```
```{r}
#Akurasi data training
SSE1<-winter1$SSE
MSE1<-winter1$SSE/length(trainter)
RMSE1<-sqrt(MSE1)
akurasi1 <- matrix(c(SSE1,MSE1,RMSE1))
row.names(akurasi1)<- c("SSE", "MSE", "RMSE")
colnames(akurasi1) <- c("Akurasi")
akurasi1
```

```{r}
SSE1.opt<-winter1.opt$SSE
MSE1.opt<-winter1.opt$SSE/length(trainter)
RMSE1.opt<-sqrt(MSE1.opt)
akurasi1.opt <- matrix(c(SSE1.opt,MSE1.opt,RMSE1.opt))
row.names(akurasi1.opt)<- c("SSE1.opt", "MSE1.opt", "RMSE1.opt")
colnames(akurasi1.opt) <- c("Akurasi")
akurasi1.opt
```

```{r}
akurasi1.train = data.frame(Model_Winter = c("Winter 1","Winter1 optimal"),
                            Nilai_SSE=c(SSE1,SSE1.opt),
                            Nilai_MSE=c(MSE1,MSE1.opt),Nilai_RMSE=c(RMSE1,RMSE1.opt))
akurasi1.train
```
```{r}
#Akurasi Data Testing
forecast1<-data.frame(forecast1)
testing.ts<-data.frame(testter)
selisih1<-forecast1-testing.ts
SSEtesting1<-sum(selisih1^2)
MSEtesting1<-SSEtesting1/length(testter)

forecast1.opt<-data.frame(forecast1.opt)
selisih1.opt<-forecast1.opt-testing.ts
SSEtesting1.opt<-sum(selisih1.opt^2)
MSEtesting1.opt<-SSEtesting1.opt/length(testter)
```

```{r}
winter2 <- HoltWinters(trainter,alpha=0.2,beta=0.1,gamma=0.3,seasonal = "multiplicative")
winter2$fitted
```

```{r}
xhat2 <- winter2$fitted[,2]

winter2.opt<- HoltWinters(trainter, alpha= NULL,  beta = NULL, gamma = NULL, seasonal = "multiplicative")
winter2.opt$fitted
```
```{r}
xhat2.opt <- winter2.opt$fitted[,2]
```

```{r}
forecast2 <- predict(winter2, n.ahead = 19)
forecast2.opt <- predict(winter2.opt, n.ahead = 19)
```

```{r}
#Akurasi data training
SSE2<-winter2$SSE
MSE2<-winter2$SSE/length(trainter)
RMSE2<-sqrt(MSE2)
akurasi1 <- matrix(c(SSE2,MSE2,RMSE2))
row.names(akurasi1)<- c("SSE2", "MSE2", "RMSE2")
colnames(akurasi1) <- c("Akurasi lamda=0.2")
akurasi1
```

```{r}
SSE2.opt<-winter2.opt$SSE
MSE2.opt<-winter2.opt$SSE/length(trainter)
RMSE2.opt<-sqrt(MSE2.opt)
akurasi1.opt <- matrix(c(SSE2.opt,MSE2.opt,RMSE2.opt))
row.names(akurasi1.opt)<- c("SSE2.opt", "MSE2.opt", "RMSE2.opt")
colnames(akurasi1.opt) <- c("Akurasi")
akurasi1.opt
```

```{r}
akurasi2.train = data.frame(Model_Winter = c("Winter 1","winter2 optimal"),
                            Nilai_SSE=c(SSE2,SSE2.opt),
                            Nilai_MSE=c(MSE2,MSE2.opt),Nilai_RMSE=c(RMSE2,RMSE2.opt))
akurasi2.train
```

```{r}
forecast2<-data.frame(forecast2)
testing.ts<-data.frame(testter)
selisih2<-forecast2-testing.ts
SSEtesting2<-sum(selisih2^2)
MSEtesting2<-SSEtesting2/length(testter)
RMSEtesting2<- sqrt(MSEtesting2)

forecast2.opt<-data.frame(forecast2.opt)
selisih2.opt<-forecast2.opt-testing.ts
SSEtesting2.opt<-sum(selisih2.opt^2)
MSEtesting2.opt<-SSEtesting2.opt/length(testter)
RMSEtestingopt<- sqrt(MSEtesting2.opt)

akurasi2.train = data.frame(Model_Winter = c("Winter 1","winter2 optimal"),
                            Nilai_SSE=c(SSEtesting2,SSEtesting2.opt),
                            Nilai_MSE=c(MSEtesting2,MSEtesting2.opt),Nilai_RMSE=c(RMSEtesting2,RMSEtestingopt))
akurasi2.train
```
